/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JRootPane;

/**
 *
 * @author Rz Rasel
 */
public class APIDashboard extends javax.swing.JFrame {

    private JFrame jFrame;

    /**
     * Creates new form APIDashboard
     */
    public APIDashboard() {
        initComponents();
        jFrame = this;
        setTitle("API - Dashboard");
        setLocationRelativeTo(this);
        //setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CL‌​OSE);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        /*
        this.hide();
        frm1.setVisible(false);
        frm1.setDefaultCloseOperation(frm1.DISPOSE_ON_CLOSE);*/
        //getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        //setUndecorated(true);
        //this.jframe.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        /*addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent argWindowEvent) {
                System.out.println("CLOSE");
                //argWindowEvent.getWindow().setVisible(false);
                //return;
                try {
                    wait();
                } catch (InterruptedException e) {
                    //Logger.getLogger(WindowsActions.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });*/
        sysMenuItemExit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent argActionEvent) {
                System.exit(0);
            }
        });
        sysMenuItemAPINewProject.addActionListener(new OnMenuItemActionListener(jFrame, new APINewProject()));
        sysMenuItemAPINewTemplate.addActionListener(new OnMenuItemActionListener(jFrame, new APINewTemplate()));
        sysMenuItemAPINewPages.addActionListener(new OnMenuItemActionListener(jFrame, new APINewPages()));
        /*sysMenuItemAPINewTemplate.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent argActionEvent) {
                JFrame jFrameChild = new APINewTemplate();
                jFrameChild.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                jFrameChild.setLocationRelativeTo(jFrame);
                jFrameChild.setVisible(true);
            }
        });*/
    }

    private class OnMenuItemActionListener implements ActionListener {

        private JFrame jFrameParent = null;
        private JFrame jFrameChild = null;

        public OnMenuItemActionListener(JFrame argJFrameParent, JFrame argJFrameChild) {
            jFrameParent = argJFrameParent;
            jFrameChild = argJFrameChild;
        }

        public void actionPerformed(ActionEvent argActionEvent) {
            if (jFrameChild != null && jFrameParent != null) {
                jFrameChild.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                jFrameChild.setLocationRelativeTo(jFrameParent);
                jFrameChild.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sysMenuBarTop = new javax.swing.JMenuBar();
        sysMenuFile = new javax.swing.JMenu();
        sysMenuItemExit = new javax.swing.JMenuItem();
        sysMenuEdit = new javax.swing.JMenu();
        sysMenuAPIOperation = new javax.swing.JMenu();
        sysMenuItemAPINewProject = new javax.swing.JMenuItem();
        sysMenuItemAPINewTemplate = new javax.swing.JMenuItem();
        sysMenuItemAPINewPages = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sysMenuFile.setText("File");

        sysMenuItemExit.setText("Exit");
        sysMenuFile.add(sysMenuItemExit);

        sysMenuBarTop.add(sysMenuFile);

        sysMenuEdit.setText("Edit");
        sysMenuBarTop.add(sysMenuEdit);

        sysMenuAPIOperation.setText("API Operation");

        sysMenuItemAPINewProject.setText("New Project");
        sysMenuAPIOperation.add(sysMenuItemAPINewProject);

        sysMenuItemAPINewTemplate.setText("New Template");
        sysMenuAPIOperation.add(sysMenuItemAPINewTemplate);

        sysMenuItemAPINewPages.setText("New Pages");
        sysMenuAPIOperation.add(sysMenuItemAPINewPages);

        sysMenuBarTop.add(sysMenuAPIOperation);

        setJMenuBar(sysMenuBarTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APIDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APIDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu sysMenuAPIOperation;
    private javax.swing.JMenuBar sysMenuBarTop;
    private javax.swing.JMenu sysMenuEdit;
    private javax.swing.JMenu sysMenuFile;
    private javax.swing.JMenuItem sysMenuItemAPINewPages;
    private javax.swing.JMenuItem sysMenuItemAPINewProject;
    private javax.swing.JMenuItem sysMenuItemAPINewTemplate;
    private javax.swing.JMenuItem sysMenuItemExit;
    // End of variables declaration//GEN-END:variables
}
/*
http://www.javaworld.com/article/2071334/adding-drop-support-to-jtree.html
https://stackoverflow.com/questions/1542081/netbeans-entering-items-in-a-jcombobox
https://stackoverflow.com/questions/9535260/populate-a-jcombobox-in-netbeans-7-1
JTree basic tutorial and examples
http://www.codejava.net/java-se/swing/jtree-basic-tutorial-and-examples

https://stackoverflow.com/questions/7928839/adding-and-removing-nodes-from-a-jtree

*/